swapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swpeople.urls'))
]

swpeople/urls.py
from django.urls import path

from swpeople import views

app_name = "swpeople"

urlpatterns = [
    path('', views.GetPeople.as_view(), name="get_people"),
    path('get_people_details/<int:id>', views.GetPeopleDetails.as_view(), name="get_people_details"),
    path('fetch/', views.FetchPeople.as_view(), name="fetch_people"),
]

swpeople/models.py
from django.db import models


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class FileMetaData(TimeStampMixin):
    filename = models.CharField(max_length=100)

    def __str__(self):
        return self.filename

swpeople/views.py
import os

import petl as etl
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.generic import ListView, View

from swapi.settings import BASE_DIR
from .bootstrap import people_service
from .models import FileMetaData


class GetPeople(ListView):
    model = FileMetaData
    ordering = ['-created_at']
    template_name = "swpeople/index.html"
    context_object_name = 'objs'


class FetchPeople(View):
    _people_service = people_service

    def get(self, request, *args, **kwargs):
        self._people_service.fetch_people()
        return redirect("swpeople:get_people")


class GetPeopleDetails(View):
    template_name = "swpeople/details.html"
    _people_service = people_service

    def get(self, request, *args, **kwargs):
        request_get = dict(request.GET)
        file_meta_data = self._people_service.get_file_meta_data(kwargs["id"])

        if file_meta_data.id != request.session.get("file_id"):
            request.session.flush()
            request.session["file_id"] = file_meta_data.id
        if (rows := request.session.get("rows")) and request.GET.get("load_more"):
            rows += 10
        else:
            rows = 10
        request.session["rows"] = rows

        file_path = os.path.join(BASE_DIR, "files")
        table = etl.fromcsv(os.path.join(file_path, file_meta_data.filename))
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            filter_params = request_get.get("filter_names[]")
            if filter_params:
                table = etl.aggregate(table, key=tuple(filter_params), aggregation=len, value=tuple(filter_params))
                table = etl.rename(table, "value", "count")
                table = etl.dicts(etl.rowslice(table, rows))

                html = render_to_string(self.template_name,
                                        {"table": table, "table_headers": table[0].keys(), "obj": file_meta_data})
                return HttpResponse(html)
        table = etl.dicts(etl.rowslice(table, rows))

        return render(request, self.template_name,
                      {"table": table, "table_headers": table[0].keys(), "obj": file_meta_data})

swpeople/templates/swpeople/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Jquery -->
    <script
            src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>SW People Details</title>
</head>
<body>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <span><span class="navbar-brand mb-0 h1">Star Wars</span><span class="navbar-brand mb-0">Explorer</span> <a href='{% url "swpeople:get_people" %}'>Collections</a></span> 
  </div>
</nav>
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

swpeople/templates/swpeople/details.html
{% extends "swpeople/base.html" %}
{% block content %}

<div id="checkboxes" class="pt-3 ps-2">
    <p>
        {% for th in table_headers %}
            <input type="checkbox" class="btn-check" id="btn-check-outlined{{ forloop.counter }}"
                   autocomplete="off" name="{{ th }}">
            <label class="btn btn-outline-primary" for="btn-check-outlined{{ forloop.counter }}">{{ th }}</label>
        {% endfor %}
        <button type="button" class="btn btn-success" id="filter_button" style="margin-left: 3%;">Filter</button>
    </p>
</div>
<div>
<table class="table table-striped">
  <thead>
    <tr>
      {% for th in table_headers %}
      <th scope="col">{{ th }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
  {% for td in table %}
   <tr>
      {% if td.name %}<td scope="col">{{ td.name }}</td>{% endif %}
      {% if td.height %}<td scope="col">{{ td.height }}</td>{% endif %}
      {% if td.mass %}<td scope="col">{{ td.mass }}</td>{% endif %}
      {% if td.hair_color %}<td scope="col">{{ td.hair_color }}</td>{% endif %}
      {% if td.skin_color %}<td scope="col">{{ td.skin_color }}</td>{% endif %}
      {% if td.eye_color %}<td scope="col">{{ td.eye_color }}</td>{% endif %}
      {% if td.birth_year %}<td scope="col">{{ td.birth_year }}</td>{% endif %}
      {% if td.gender %}<td scope="col">{{ td.gender }}</td>{% endif %}
      {% if td.homeworld %}<td scope="col">{{ td.homeworld }}</td>{% endif %}
      {% if td.edited %}<td scope="col">{{ td.edited }}</td>{% endif %}
      {% if td.url %}<td scope="col">{{ td.url }}</td>{% endif %}
      {% if td.date %}<td scope="col">{{ td.date }}</td>{% endif %}
      {% if td.count %}<td scope="col">{{ td.count }}</td>{% endif %} 
    </tr>
  {% endfor %}
  </tbody>
</table>
    </div>
<div class="row">
    <div class="col-3 mb-3">
        <a href='{% url "swpeople:get_people_details" id=obj.id %}?load_more=true' class="btn btn-primary load-more ps-2" id="load-more">Load More</a>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#filter_button").click(function () {
            loadTable("{% url "swpeople:get_people_details" id=obj.id %}");
        });
        $("#load-more").click(function (e) {
            e.preventDefault();
            loadTable("{% url "swpeople:get_people_details" id=obj.id %}?load_more=true");
        });
    });
    function loadTable(url) {
        let selected = [];
            $('#checkboxes input:checked').each(function () {
                selected.push($(this).attr('name'));
            });
            $.ajax({
                type: 'GET',
                url: url,
                data: {"filter_names": selected},
                success: function (response) {
                    $(".table").replaceWith($(response).find(".table"));
                },
                error: function (response) {
                    console.log(response)
                }
            })
    }
</script>
{% endblock %}

swpeople/templates/swpeople/index.html
{% extends "swpeople/base.html" %}
{% block content %}
<div class="ms-3 pb-3">
  <h2 class="mt-3">Collections </h2><a href='{% url "swpeople:fetch_people" %}' class="btn btn-success mt-2">Fetch</a>  
</div>

<div>
    <table class="table">
    {% for obj in objs %}
    <tr>
        <td>
            <a class="ps-3" href='{% url "swpeople:get_people_details" id=obj.id %}'>{{obj.created_at}}</a>
        </td>
    </tr>
{% endfor %}
</table>
</div>
{% endblock %}